https://arxiv.org/pdf/1603.07285

<h1> what are convolutions? </h1>
cnn is a type of deep learning algo used for feature extractio
keren is the filter layer which multiplies with the image tensor
padding:
using cnn, the nn will lose its feature in the edges thats for sure: 
<link> https://www.digitalocean.com/community/tutorials/padding-in-convolutional-neural-networks</link>

but we can add padding to minize the loss of feature on the ediges
a 5x5 pic going through 3x3 fileter would result in the loss of 2 pixel (3-1)
thus adding padding of 2 pixel would save the features of the image


img = (x,y), filter/kernel = (m,n)
final tenson = 
x - m + 1 or 5 - 3 + 1,
y - n + 1 or 5 - 3 + 1

<p>

convo layer:

kernel init
kernel * input tensor

pooling: downsampling the input array 
28x28 -> 14x14
</p>

<p>
    Filter also have depth just like image
    1 filter will produce 1 output which can have depth

</p>

F=Filter dim
K=depth of a filter

In [3]:
import numpy as np

In [26]:
x,y

(array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]]))

In [29]:
x = np.arange(0,4).reshape(2,2)
y = np.arange(4,8).reshape(2,2)
np.dot(x,y)
np.sum(x * y) 



38

In [16]:
# If we add a kernel of size ks by ks (with ks an odd number), the necessary padding on each side to keep the same shape is ks/2
class Cnn:
    def __init__(self, inputArr, k_dim = 3, padding = True, strding=1):
        self.input = inputArr
        self.strding = 1 
        self.padding = k_dim-1
    
    def forward(self):
        w1 = kernel(dim)
        inputArr_wp = addPadding(self.input) 
        inptArr2 = 


class Cnn
    

In [2]:
def randDim(dim):
    return np.random.rand(dim, dim)

In [8]:
# i want to multiply m1[i, j] with m[i, j] and return the sum of all the output 


In [7]:
# n_tensor = tensor.shape[0]
tensor = randDim(6)
kernel= randDim(4)
def outPutDim(inputDim, k_dim, pad, strid):
    return int((( inputDim - k_dim) + (2 * pad))/strid + 1)

# n_tensor = addPadding(n_tensor)
outPutDim(tensor.shape[0], kernel.shape[0], 1, 2)

3

In [29]:
inpTen = np.arange(0, 25).reshape(5, 5)
ker = np.arange(0, 9).reshape(3,3)
    # inpTen, ker
striding = 1
padding = 1
oDim = int(((inpTen.shape[0] - ker.shape[0]) + (2 * padding))/striding + 1) #2+2/2 1
print(oDim)
inpTen = addPadding(inpTen, padding)
out = np.zeros(oDim * oDim)

startCols = ker.shape[0]-1 # start cols would target top right edge of kernel and input array overlap
maxCols = inpTen.shape[0]  #maxCols would be till the end of the input Arry hence 
maxRows = inpTen.shape[0] - ker.shape[0] + 1 #max rows will depend upop input and kernel as we dont want kernel to go out of bound of input

# [[print(i,j) for j in range(startCols, maxCols, striding)] for i in range(0, maxRows)];

[[print(stridingMatMulSum(i, j, ker)) for j in range(startCols, maxCols, striding)] for i in range(0, maxRows, striding)];

5
48.0
56.0
64.0
72.0
63.0
88.0
96.0
104.0
112.0
98.0
128.0
136.0
144.0
152.0
133.0
168.0
176.0
184.0
192.0
168.0
105.0
110.0
115.0
120.0
96.0


In [28]:
import numpy as np

def mse(pred, y):
    return ((y - pred)**2)*0.5

def softmax(x): 
    return np.exp(x)/sum(np.exp(x))

def matmul(inpTen, weight, bias):
    # print(weight.shape, inpTen.shape)
    return weight @ inpTen + bias # Inp(16, 1)

def relu(inputTen):
    return inputTen * (inputTen > 0)

def crossEntropyLoss(preds, target):
    # preds_clip = (preds == preds.max()) *1
    return (-(target * np.log(preds))).max()


In [161]:
# print(x)
epsilon=1e-12
np.clip(x, epsilon, 1-epsilon)
x

array([[-0.17412229],
       [ 0.43759796],
       [ 0.56831197],
       [-0.67134861],
       [ 0.18865578],
       [ 0.19140119],
       [ 1.95316819],
       [-0.38867115],
       [-0.71889078],
       [-0.79060418]])

In [164]:
new_mat = np.zeros(x.shape)  # our zeros and ones will go here
c= new_mat[np.argmax(x, axis=0), np.arange(x.shape[1])] = 1
c

1

In [5]:
inpTen = np.arange(0, 784).reshape(28,28)

strid = 2
padding = 1

class convo1d:
    def __init__(self):
        self.input = inpTen 
        # self.filter_Dim =
        self.padding = padding
        self.strid= strid
        
    def feedforward(self):
        self.c1 = convo(self.input, self.strid, self.padding)
        self.c2 = convo(self.l1, self.strid, self.padding)
        self.c3 = 
        self.



def addPadding(m1, padding=1):
    int(padding)
    if padding == 0: return m1
    
    # row padding init
    m2 = np.zeros((padding, m1.shape[1])) #m1 =3x3 then m2 = 1x3
    
    # adding rows of padding
    m3 = np.concatenate((m1, m2), axis=0) #m1 = 3x3 & m2=1x3 at axis = 0 column match() at axis = 1 row match
    m3 = np.concatenate((m2, m3), axis=0) 
    m3 # 5x3
    # to add 2 column of zerors
    
    # init col of padding
    m4 = np.zeros((m3.shape[0], padding)) #m4 = 5 x 1
    
    # adding col padding to the arr
    m3 = np.concatenate((m3, m4), axis=1)
    m3 = np.concatenate((m4, m3), axis=1)
    m3.shape
    return m3
        
def stridingMatMulSum(i, j, ker, inpTen):
    k_dim = ker.shape[0]
    
    rowStart = i
    rowEnd = k_dim + i
    
    colEnd = j + 1  
    colStart = (j+1)-k_dim
    # print(np.dot(inpTen[rowStart:rowEnd, colStart:colEnd], ker))
    return (inpTen[rowStart:rowEnd, colStart:colEnd] * ker).max();


def convo2d(inpTen, striding, padding):
    # init the kernel in the convo layer
    ker = np.random.randn(3,3)

    
    # calculating dim
    oDim = int(((inpTen.shape[0] - ker.shape[0]) + (2 * padding))/striding + 1) #2+2/2 1
    print(oDim)

    # padding
    inpTen_wp = addPadding(inpTen, padding)
    
    startCols = ker.shape[0]-1 # start cols would target top right edge of kernel and input array overlap
    maxCols = inpTen_wp.shape[0]  #maxCols would be till the end of the input Arry hence 
    maxRows = inpTen_wp.shape[0] - ker.shape[0] + 1 #max rows will depend upop input and kernel as we dont want kernel to go out of bound of input
    
    collect = []
    [[collect.append(stridingMatMulSum(i, j, ker, inpTen_wp)) for j in range(startCols, maxCols, striding)] for i in range(0, maxRows, striding)];
    out = np.array(collect).reshape(oDim, oDim)
    return out


14


(14, 14)

In [2]:
import torchvision 
import torchvision.datasets

data = torchvision.datasets.MNIST("~/.data", train=True, download=False, transform="tensor")
len(data)



60000

In [206]:

data = np.asarray(data, dtype="object")
data.shape
# np.array(datada)

(60000, 2)

In [233]:
# Iterate over the DataLoader
for batch_idx, (images, labels) in enumerate(train):
    # Process only the first 5 images and labels from the batch
    for i in range(5):
        print(f"Image {i + 1}:")
        print(f"Tensor Shape: {images[i].shape}")  # Shape: [channels, height, width]
        # print(f"Tensor Values: {images[i]}")      # Tensor values
        print(f"Label: {labels[i]}")              # Corresponding label
        print("-" * 40)
    # Exit after processing the first 5 images
    break


Image 1:
Tensor Shape: torch.Size([1, 28, 28])
Label: 5
----------------------------------------
Image 2:
Tensor Shape: torch.Size([1, 28, 28])
Label: 0
----------------------------------------
Image 3:
Tensor Shape: torch.Size([1, 28, 28])
Label: 4
----------------------------------------
Image 4:
Tensor Shape: torch.Size([1, 28, 28])
Label: 1
----------------------------------------
Image 5:
Tensor Shape: torch.Size([1, 28, 28])
Label: 9
----------------------------------------


In [11]:
import torchvision
import torchvision.datasets
from torch.utils.data import DataLoader
from torchvision import transforms

transform = transforms.Compose([
    transforms.ToTensor(),              
])

# Create dataset with transforms
data = torchvision.datasets.MNIST(
    "~/.data",
    train=True,
    download=False,
    transform=transform  # Apply the transformations
)

# Create DataLoader
train = DataLoader(data, batch_size=8)


In [22]:
def getData_hotEnco(data): 
    data_bs = []
    label = []
    
    for bs, (image, label) in enumerate(data):
        for i in range(5):
            data_bs.append(image[i])
            # label.append(label[i])
        break
    
    train_np = np.array(data_bs)
    label = np.array(label)
    
    train_np_sq = np.squeeze(train_np)
    hot_enco_vect = getHotEnc(label)
    return train_np_sq, hot_enco_vect

def getHotEnc(label):
    hot_enco = []
    for i in label:
        vect = np.zeros(10)
        vect[i] = 1
        hot_enco.append(vect)
    
    hot_enco_np = np.array(hot_enco)
    return hot_enco_np

In [13]:

# adding loss together 
class Linear:
    def __init__(self, bs=8):
        self.w1 = np.random.randn(16, 784).astype(np.float32)
        self.b1 = np.random.randn(16, 1).astype(np.float32)
        self.w2 = np.random.randn(10, 16).astype(np.float32)
        self.b2 = np.random.randn(10, 1).astype(np.float32)

        
    def forward(self, inpTen, target):
        self.inpTen = inpTen # 28x28 
        self.inpTen = self.inpTen.reshape(784, 1)
        
        l1 = matmul(self.inpTen, self.w1, self.b1)
        l1 = relu(l1)
        # ->16x1
        out = matmul(l1, self.w2, self.b2)  # 10x16@16x1 -> 10x1
        out = out.flatten() #10
        
        self.preds = softmax(out)

        self.loss = crossEntropyLoss(self.preds, target) # y and out should be a vector
        # print("preds",self.preds)
        print("loss:", self.loss)
        return self.preds

    def backward(self):
        


# inpTen = np.float128(np.random.randn(28, 28))
# target  = np.array([0,0,0,0,0,1,0,0,0,0])
# x = Linear(inpTen)
# x.forward(target)

# x.getLoss()
# calulation of gradinats of the loss wrt weights

        


In [1]:
def LinInit(train):
    x = Linear()
    x_np, y_np = getData_hotEnco(train)
    print(x_np.shape, y_np.shape)
    for i in range(2):
        print(x.forward(inpTen=x_np[i],target=y_np[i]))

# LinInit(train)

In [7]:
import numpy as np

def weights(dim):
    return np.random.randn(dim,1)

weights(10).shape

(10, 1)

<h1>Backward Prop</h1>

In [ ]:
Error=> mse(y'2 - y2)

In [ ]:
error rate of change wrt w

<h1>HXWXC</h1>

what are gradinats and why do we need them?

gradinast is the rate of change of function wrt inputt

autograd calculates gradinets and stores them in the resp tensors in .grad 


autograd keeps tensors -> excuted functions on those tensors -> along with the new tensors

In [1]:
import matplotlib.pyplot as plt
import numpy as np

x = np.array([2, 3, 4])
y = np.array([6, 8, 12])

In [62]:
x, y

(array([ 2,  7, 12]), array([ 6,  4, 15]))

In [63]:
def q(x, y):
    return 3*x**3 - y**2


In [68]:
z = q(x, y)

In [74]:
f = np.array([-12, 17 , 48])

In [75]:
print(f)
np.gradient(f)

[-12  17  48]


array([29., 30., 31.])

In [112]:
class backward:
    def __init__(self, tensor):
        self.tens = np.array(tensor)
        self.grad = np.gradient(self.tens)

    def __call__(self):
        return self.tens


In [139]:
q = backward(f)

In [138]:
q.backwar()

AttributeError: 'backward' object has no attribute 'backwar'

In [142]:
q.grad

array([29.012, 30.   , 30.988])

In [136]:
f[1] = f[1] + (12) * 0.001


In [129]:
f[1] = 17.021

In [134]:
f  = f.astype("float")

In [3]:
def relu(x):
    return np.max(0, x)

In [4]:
def dot(m1, m2):
    return np.dot(m1, m2)

In [7]:
def loss(y_, y):
    return np.sqrt(np.square(y_ - y))

In [8]:
loss(-2, 3)

5.0

In [9]:
tens = np.random.randn(3,3)

In [10]:
tens

array([[1.82130991, 0.65891524, 0.39876975],
       [0.70741533, 0.65937678, 0.91816523],
       [0.51885255, 0.05000812, 0.30888045]])

In [ ]:
w = w * lr*grad(dL/dw)

In [ ]:
dL/dW = L/softmax * softmax/relu * relu/w 

In [ ]:
loss = x - x'
f(x)= x - x'



In [ ]:
# m1 -> 28x28 -> 784 dot 
# m2 -> 

def matMul(m1, m2)

In [ ]:
def chunkz(x, bs):
    for i in range(0, len(x), sz): yield x[i+ i+sz]


In [2]:
import numpy as np

In [4]:
img = np.random.randint(0, 255, size=(728, 1))

In [7]:
img = img.reshape(728, 1)

In [10]:
weights = np.random.randn(128, 1)

In [13]:
weights.shape, img.shape

((128, 1), (728, 1))

In [18]:
from sympy import symbols,diff
x,y = symbols('x y')
diff(x**2, x)

2*x

In [19]:
def lin_grad(inp, out, w, b):
    inp.g = out.g @ w.t()
    w.g = (inp.unsqueeze(-1)  *  out.g.unsqueeze(1)).sum(0)
    b.g = out.g.sum(0)
    

In [ ]:
def for_and_back(inp, targ):
    l1= lin(inp, w1, b1)
    l2 = relu(l1)
    out = lin(l2, w2, b2)
    diff = out[:, 0] - targ
    loss = diff.pow(2).mean()

    # backward pass 
    out.g = 2.diff[:, None] / inp.shape[0]
    lin_grad(l2, out, w2, b2)
    l1.g

In [25]:
# loss = 


0.707106781186548/x**0.5

In [26]:

def forward_and_backward(inp, targ):
    # forward pass:
    l1 = lin(inp, w1, b1)
    l2 = relu(l1)
    out = lin(l2, w2, b2)
    diff = out[:,0]-targ
    loss = diff.pow(2).mean()
    
    # backward pass:
    out.g = 2.*diff[:,None] / inp.shape[0]
    lin_grad(l2, out, w2, b2)
    l1.g = (l1>0).float() * l2.g
    lin_grad(inp, l1, w1, b1)
     

In [28]:
def lin_grad(inp, out, w, b):
    # grad of matmul with respect to input
    inp.g = out.g @ w.t()
    print(inp.g.shape)
    w.g = (inp.unsqueeze(-1) * out.g.unsqueeze(1)).sum(0)
    print(w.g.shape)
    b.g = out.g.sum(0)
    print(b.g.shape)

In [36]:
def lin(inp, w1, b1):
    return inp@w1 + b1

l2 = lin(img, weights.T, 0)


In [49]:
def relu(inp):
    return np.max(0, inp)

In [64]:

x = np.random.randn(3,3)
# x =x.flatten().reshape(9)

In [67]:
x[:, None, :].shape

(3, 1, 3)

In [37]:
l2.shape

(728, 128)

In [35]:
print(img.T.shape, weights.T.shape)

(1, 728) (1, 128)
